module.exports = function(grunt) {
  grunt.initConfig({
    concat: {
      dist: {
        src: ["index.html"],
        dest: "build/index.html"
      }
    },
    replace: {
      dist: {
        options: {
          patterns: [
            {
              match: /<link rel="stylesheet" type="text\/css" href="css\/main.css">/,
              replacement: '\n<style>\n<%= grunt.file.read("css/main.css").trim() %>\n</style>\n'
            },
            {
              match: /<script type="text\/javascript" src="js\/main.js"><\/script>/,
              replacement: '\n<script>\n<%= grunt.file.read("js/main.js").trim() %>\n</script>\n'
            },
            {
              match: /<div class="animore-autogenerated-helper">.*<\/div>/,
              replacement: ''
            }
          ]
        },
        files: [
          {expand: true, flatten: true, src: ['index.html'], dest: 'build/'}
        ]
      }
    },
    less: {
      build: {
        files: {
          "css/main.css": "css/main.less"
        }
      }
    },
    zip: {
      'build/animore.zip': [
        'index.html', 
        'css/main.css',
        'js/main.js',
        'build/index.html'
      ]
    },
    connect: {
      server: {
        options: {
          port: 8000,
          open: true
        },
      },
    },
    watch: {
      options: {
          livereload: true,
      },
      style: {
          files: ['**/*.css'],
          tasks: ['less'],
      },
      content: {
          files: ['**/*.js', '**/*.html'],
          tasks: []
      }
    },
  });

  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-connect');
  grunt.loadNpmTasks('grunt-replace');
  grunt.loadNpmTasks('grunt-zip');
  grunt.loadNpmTasks('grunt-contrib-less');
  grunt.loadNpmTasks('grunt-contrib-watch');

  grunt.registerTask('dev', ['connect', 'watch']);
  grunt.registerTask('build', ['less', 'replace', 'zip']);
  grunt.registerTask('default', ['build']);
};